version: "2.1"

networks:
  aether:
    external:
      name: aether_internal

services:

# ---------------------------------
  # Gather container
  # ---------------------------------

  gather:
    extends:
      file: docker-compose-base.yml
      service: gather-base
    networks:
      aether:
        aliases:
          - gather.local
