language: python
python:
  - "3.7"
services:
- docker
cache: pip
before_script:
- docker login -u ehealthafricadevops -p $DOCKER_HUB_PASSWORD

matrix:
  fast_finish: true
  include:

    - name: "Test"
      stage: test
      install: true
      script: "./scripts/run_travis.sh"

    - name: "Release"
      stage: deploy
      install: true
      script: "./scripts/release.sh"
      # release only if tag like #.#.#
      if: (tag =~ ^[0-9]+(\.[0-9]+){2}$)