language: python
python:
  - "2.7"
services:
- docker
cache: pip
before_script:
- docker login -u ehealthafricadevops -p $DOCKER_HUB_PASSWORD
install: bash bin/travis-build.bash
script: sh bin/travis-run.sh

deploy:
- provider: script
  script: "./scripts/release.sh"
  skip_cleanup: true
  on:
    all_branches: true
    if: [[ ($TRAVIS_BRANCH =~ ^release\-[0-9]+\.[0-9]+[\.0-9]*$) || ($TRAVIS_TAG =~ ^[0-9]+\.[0-9]+[\.0-9]*$) ]]
