version: "2.1"

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:
  ckan-consumer:
    extends:
      file: docker-compose-base.yml
      service: ckan-consumer-base
    environment:
      CKAN_CONSUMER_CONFIG_PATH: "/code/conf/consumer/consumer.json"
      CKAN_CONSUMER_KAFKA_CONFIG_PATH: "/code/conf/consumer/kafka.json"
      LOG_LEVEL: "DEBUG"
      CONSUMER_PORT: 9009
    networks:
      - aether
    ports:
      - 9009:9009
