version: "2.4"
services:

  ckan-consumer-base:
    build: consumer
    image: aether-ckan-consumer
    stdin_open: true
    volumes:
      - ./consumer:/code
    environment:
      PYTHONUNBUFFERED: 0
    command: start
