version: "2.1"
services:
  consumer-test:
    extends:
      file: docker-compose-base.yml
      service: ckan-consumer-base
    environment:
      TENANCY_HEADER: x-oauth-realm

      CONSUMER_NAME: 'CKAN-TEST'

      EXPOSE_PORT: 9013
      LOG_LEVEL: "DEBUG"
      CKAN_CONSUMER_CONFIG_PATH: "/code/tests/conf/consumer.json"
      CKAN_CONSUMER_KAFKA_CONFIG_PATH: "/code/tests/conf/kafka.json"
      CONNECT_RETRY_WAIT: 1
      STARTUP_CONNECTION_RETRY: 3

      # redis
      REDIS_DB: 2
      REDIS_HOST: redis-test
      REDIS_PORT: 6379
      REDIS_PASSWORD: testpassword

      KAFKA_URL: kafka-test:29092
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: root
      SASL.PASSWORD: 09049a938686107c15ed6748010e2f1b

  ckan-test:
    image: ehealthafrica/ckan:2.8.0-rc
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - DATASTORE_READONLY_PASSWORD=datastore
      - DS_RO_PASS=datastore
      - CKAN_SITE_URL=http://ckan-test:5001
      - CKAN_PORT=5001
      - CKAN_MAX_UPLOAD_SIZE_MB=20000
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@ckanpg-test/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:ckan@ckanpg-test/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:datastore@ckanpg-test/datastore
      - CKAN_SOLR_URL=http://solr-test:8984/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6380/2
      - CKAN_DATAPUSHER_URL=http://datapusher:8801
      - POSTGRES_PASSWORD=testpassword
    depends_on:
      - ckanpg-test
      - solr-test
      - redis-test
    ports:
      - 5000:5000
    restart: on-failure

  ckanpg-test:
    build:
      context: .
      dockerfile: consumer/tests/ckan/postgresql/Dockerfile
      args:
        - DS_RO_PASS=datastore
        - POSTGRES_PASSWORD=ckan
    environment:
      - DS_RO_PASS=datastore
      - POSTGRES_PASSWORD=ckan

  solr-test:
    build:
      context: .
      dockerfile: consumer/tests/ckan/solr/Dockerfile

  redis-test:
    image: redis:alpine
    command: >
      redis-server
      --requirepass testpassword
      --notify-keyspace-events KEA
      --appendonly yes
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
