version: "3"
services:
  consumer-test:
    extends:
      file: docker-compose-base.yml
      service: ckan-consumer-base
    volumes:
      - ./consumer/tests:/code/tests
      - ./db/:/srv/app/db/
    environment:
      TENANCY_HEADER: x-oauth-realm
      REDIS_DB: 0
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: password

      CONSUMER_NAME: 'CKAN-TEST'

      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_SASL_USERNAME}
      SASL.PASSWORD: ${KAFKA_SASL_PASSWORD}

      EXPOSE_PORT: 9013
      LOG_LEVEL: "DEBUG"
      CKAN_CONSUMER_CONFIG_PATH: "/code/tests/conf/consumer.json"
      CKAN_CONSUMER_KAFKA_CONFIG_PATH: "/code/tests/conf/kafka.json"
      CONNECT_RETRY_WAIT: 1
      STARTUP_CONNECTION_RETRY: 3
