FROM python:2.7-alpine

ENV ENVIRONMENT=test

RUN apk update && \
    apk add --no-cache \
        bash \
        gcc \
        libffi-dev \
        linux-headers \
        musl-dev \
        openssl-dev

WORKDIR /srv/app

# This avoids reinstalling Python packages each time the image is rebuilt
ADD ./requirements.txt /srv/app/requirements.txt
ADD ./dev-requirements.txt /srv/app/dev-requirements.txt

RUN pip install -r requirements.txt
RUN pip install -r dev-requirements.txt

ADD . /srv/app

RUN pycodestyle ./consumer

CMD ["nosetests", "./tests"]

